services:
  app:
    build: .
    ports:
      - "3000:3000" 
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql-db:3306/${MYSQL_DATABASE}
    depends_on:
      - mysql-db
    develop:
      watch:
        - action: sync
          path: ./app    
          target: /app/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    volumes:
      - todo-db:/var/lib/mysql

  mysql-db:
    image: mysql:9.1.0
    command: --default-time-zone='+00:00'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - todo-db:/var/lib/mysql

volumes:
  todo-db:
    driver: local